version: 2

sources:
    - name: staging
      database: dtc-de-project-381912
      schema: bike_sharing_data
    
      tables:
        - name: sharing_trips
        - name: stations
        - name: weather